### ISSUE TITLE
Arity Exception when loading REPL

### ISSUE THREAD

**Issue by matt3ho** [cursive-ide/cursive#1681] opened 2017-03-11 23:03 UTC
I'm connecting to a remote nREPL, which worked before the latest Mar. 10th, 2017 update without error messages.  Now, when I load it I get:

Connecting to remote nREPL server...
Clojure 1.9.0-alpha14
Error updating completions:
ArityException Wrong number of args (5) passed to: runtime/completions  clojure.lang.AFn.throwArity (AFn.java:429)

I'm using IntelliJ 2016.2

**Comment by ertugrulcetin** [comment] 2017-03-12 09:48
Yes, also I'm getting this error too.

**Comment by matt3ho** [comment] 2017-03-12 10:00
Update: for me, a simple reboot seems to have solved the problem for now, and auto-complete/detection of imported/known variables works in the REPL again

**Comment by cursive-ide** [comment] 2017-03-12 23:51
When Cursive connects to a REPL, it sends over the server-side code it needs to do completion from the remote system. This appears to be because the previous code isn't cleared out correctly, so restarting your REPL server process should work as a workaround in the meantime.

**Comment by cursive-ide** [comment] 2017-03-22 23:17
Is anyone getting this error on an ongoing basis? I can't reproduce it or figure it out, and if it's a one time thing until everyone reboots their REPLs I'm happy to leave it.

**Comment by matt3ho** [comment] 2017-03-22 23:25
For me it was a one-time thing that was fixed on a reboot and has not re-appeared, so I'm happy to have it closed.

**Comment by rauhs** [comment] 2017-03-27 09:16
I just restarted my REPLs and the error is still there. :(

**Comment by cursive-ide** [comment] 2017-03-27 23:01
@rauhs Can you try `(meta #'cursive.repl.runtime/completions)` in the REPL and see what it comes back with?

**Comment by cursive-ide** [comment] 2017-03-28 01:22
I've moved this into the next EAP build pending some more investigation.

**Comment by rauhs** [comment] 2017-03-28 05:41
```clojure
Connecting to remote nREPL server...
Clojure 1.9.0-alpha15
Error updating completions:
ArityException Wrong number of args (5) passed to: runtime/completions  clojure.lang.AFn.throwArity (AFn.java:429)
(meta #'cursive.repl.runtime/completions)
=>
{:arglists ([ns]),
 :line 31,
 :column 1,
 :file "/home/rauh/.IntelliJIdea2016.3/config/plugins/clojure-plugin/lib/runtime-1.4.0-eap1-2016.2.jar!/cursive/repl/runtime.clj",
 :name completions,
 :ns #object[clojure.lang.Namespace 0x62d4cd04 "cursive.repl.runtime"]}
```

**Comment by cursive-ide** [comment] 2017-03-29 02:15
What does `ls /home/rauh/.IntelliJIdea2016.3/config/plugins/clojure-plugin/lib/` show?

**Comment by rauhs** [comment] 2017-03-29 05:11
```
$ ls /home/rauh/.IntelliJIdea2016.3/config/plugins/clojure-plugin/lib/                                       [INS]
artem-0.5.jar                                 jps-plugin.jar
clj-stacktrace-0.2.8.jar                      jsr166y-1.7.0.jar
clj-time-0.12.2.jar                           kotlin-runtime-1.0.6.jar
clojure-1.7.0.jar                             kotlin-stdlib-1.0.6.jar
core.rrb-vector-0.0.11.jar                    rhino-1.7.7.jar
cursive-1.5.0-eap3-2016.3.jar                 runtime-1.4.0-eap1-2016.2.jar
cursive-lein-bootstrap-1.5.0-eap3-2016.3.jar  shimdandy-api-1.2.0.jar
cursive-lein-shim-1.5.0-eap3-2016.3.jar       shimdandy-impl-1.2.0.jar
fipp-0.6.8.jar                                tools.nrepl-0.2.12.jar
joda-time-2.9.4.jar
```

**Comment by cursive-ide** [comment] 2017-03-30 20:10
Ok, @rauhs has confirmed that this problem disappeared after upgrading. This is a pretty unsatisfactory solution, since I don't really understand what was happening here, but I'm going to close this issue now. Please re-open if you suffer from this problem in a non-transient way (i.e. restarting IntelliJ and/or your REPL doesn't fix it).

**Closed by cursive-ide** 2017-03-30 20:10 UTC
