### ISSUE TITLE
Highlight surrounding sexp's

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1088] opened 2015-10-05 21:51 UTC
It would be really useful to have an equivalent for [HighlightSexps](http://www.emacswiki.org/emacs/HighlightSexps) in Cursive. This could maybe hook into the same code that provides rainbow parens?

**Comment by coltnz** [comment] 2015-10-08 02:11
Edit -> Extend Selection does this, ⌘D on my machine

**Comment by danielcompton** [comment] 2015-10-08 07:45
This would be for visual purposes to show all the time, it doesn't influence selections.

**Comment by cursive-ide** [comment] 2017-01-13 21:21
This is a duplicate of #824.

**Closed by cursive-ide** 2017-01-13 21:21 UTC
Labels: Highlighting
