### ISSUE TITLE
[Cursive 1.13.4-eap7] REPL history lines now have a limit, and "Toggle Soft Wrap" keeps being automatically turned on

### ISSUE THREAD

**Issue by boschi** [cursive-ide/cursive#2925] opened 2024-07-17 13:25 UTC
I've just installed the new EAP release "Cursive 1.13.4-eap7", and noticed a few "quirks" in the REPL window:
- REPL history lines now have acap, a limit of lines displayed, and I cannot find where to remove this limit or increase the line numbers
- "Toggle Soft Wrap" keeps being automatically turned on, even after I click to turn it off

Could you please have a look into this?

My setup:
IntelliJ IDEA 2024.1.4 (Community Edition)
Build #IC-241.18034.62, built on June 20, 2024
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.9.7-1-default
GC: G1 Young Generation, G1 Old Generation
Memory: 7000M
Cores: 8
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  net.sf.opk.avro-schema-support (223.3.0)
  dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
  org.intellij.plugins.hcl (241.17890.8)
  idea.plugin.protoeditor (241.15989.49)
  name.kropp.intellij.makefile (241.14494.150)
  com.jetbrains.space (241.18034.4)
  Docker (241.18034.82)
  com.github.oowekyala.javacc (1.12.1)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-241)
  PlantUML integration (7.10.1-IJ2023.2)
  com.jetbrains.packagesearch.intellij-plugin (241.0.11)
  com.cursiveclojure.cursive (1.13.4-eap7-2024.1)
Kotlin: 241.18034.62-IJ
Current Desktop: KDE

**Comment by cursive-ide** [comment] 2024-07-18 01:17
Yes, the REPL history lines limit is due to the switch to the built-in IntelliJ console implementation, and I'm investigating why that's happening. 

Can you elaborate on when toggle soft wrap is being turned on?

**Comment by boschi** [comment] 2024-07-18 12:49
Hi Colin.

Thank you for looking into this.
It seems the "Toggle Soft Wrap" consistently being turned on when printing
anything longer than the REPL width is somewhat related to my setup at home
(external display on top of laptop one) and KDE 6... at office, on a
different setup (different external display brand and it placed beside
laptop one) I could not reproduce the error. So this must be some KDE <->
IntelliJ issue.


Regards,
Pedro Boschi

_______________
   Pedro Boschi

**Comment by cursive-ide** [comment] 2024-07-19 05:18
I've investigated the REPL output truncation, and it's controlled by the setting _Settings | Editor | General | Console | Override console cycle buffer size_. You can either increase that setting, or set it to 0 (and ignore the scary warning) to disable it completely.

No-one else has complained about the soft wrap setting and I can't reproduce it, so I'll close this issue for now. If you manage to isolate the soft wrap issue more, let me know and I can investigate it again.

**Closed by cursive-ide** 2024-07-19 05:18 UTC

**Comment by boschi** [comment] 2024-07-19 20:53
Thank you for your help!
_______________
   Pedro Boschi
