### ISSUE TITLE
Can't rename a keyword to a namespaced keyword (:thing/test is not a valid identifier)

### ISSUE THREAD

**Issue by mrzor** [cursive-ide/cursive#1429] opened 2016-06-03 17:44 UTC
The title says it all: attempting to refactor existing keyword `:test` into `:thing/test` yields 'not a valid identifier' as a red label inside the refactoring box. Refactor button remains greyed out, and I have to resort to search&replace instead.

**Comment by cursive-ide** [comment] 2016-06-13 04:38
This is a dupe of #1170.

**Closed by cursive-ide** 2016-06-13 04:38 UTC
