### ISSUE TITLE
Rename keyword grabs other keywords too

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#926] opened 2015-06-16 02:12 UTC
I was renaming `:ch` to `:send-chan`, but it also grabbed `r-ch` to rename as well. It's not really obvious, but you can see that `r-ch` is in bold in the list of references to rename.

![screenshot of intellij idea 16-06-15 2 07 28 pm](https://cloud.githubusercontent.com/assets/811954/8174479/1cad1ca2-1431-11e5-9ae2-14304e185516.png)

**Comment by danielcompton** [comment] 2015-07-26 21:31
Looks like it may relate to #800.

**Comment by cursive-ide** [comment] 2016-06-13 04:39
Right, this is a duplicate of #800.

**Closed by cursive-ide** 2016-06-13 04:39 UTC
Labels: Refactoring/Inspections
