### ISSUE TITLE
rum defc badly indented

### ISSUE THREAD

**Issue by gmp26** [cursive-ide/cursive#1438] opened 2016-06-16 17:10 UTC
Not a new issue - discussed on slack https://clojurians-log.clojureverse.org/cursive/2016-06-04.html, but the get-arounds suggested there are failing too in version 1.3.0-eap3-2016.1. Using [rum "0.9.0"].

![image](https://cloud.githubusercontent.com/assets/141701/16127465/71e4a652-33f4-11e6-9d58-1be4b63deeb3.png)

![image](https://cloud.githubusercontent.com/assets/141701/16127376/23d1ed08-33f4-11e6-999e-8879ba731f77.png)

![image](https://cloud.githubusercontent.com/assets/141701/16127502/aa0c95bc-33f4-11e6-9306-b5dec6bbcd32.png)

**Comment by cursive-ide** [comment] 2016-06-20 00:32
I can't reproduce this. The first example is definitely the problem discussed in Slack, I'll try to fix this now. However for me, the other two examples work correctly. Could you check under *Settings&rarr;Editor&rarr;Code Style&rarr;Editor&rarr;Clojure&rarr;Form Parameters* and see if you have the indentation for `rum.core/defc` customised there?

**Comment by gmp26** [comment] 2016-06-21 11:22
It does look like the last two problems are machine local. I'll be able to check the config tonight when I return to it, but I see what you see on a different machine.

**Comment by gmp26** [comment] 2016-06-21 19:41
Yes - that was the problem with cases 2 and 3. On the badly behaving machine rum/defc had value 0 whereas on the working machine it had value 'default'.  Thanks for you help! That helps explain why I was finding it so hard to preserve sensible indentation with a project edited on more than one machine.

**Comment by cursive-ide** [comment] 2016-06-21 22:36
Ok, great - I'll close this, then, since the root cause of the first issue is fixed for the next build in #775.

**Closed by cursive-ide** 2016-06-21 22:36 UTC
