### ISSUE TITLE
Repl profile name on tab

### ISSUE THREAD

**Issue by CmdrDats** [cursive-ide/cursive#2282] opened 2019-12-06 10:26 UTC
Currently, the name in the repl tabs correspond to the current namespace, but I connect to quite a few different repl's during development all with different profile names, so it would be way more useful to be able to distinguish between them with the profile name instead.

A little 'toolbar' above the current repl input showing the current namespace would seem like a more relevant place to put it, so that you can always quickly tell where you're evaluating your form to.

A nice to have would also be to configure the tab/repl background colours, to distinguish between "live" connections or "dev" connections, for instance.

**Comment by cursive-ide** [comment] 2019-12-06 10:55
Yes, I'm planning to do this very shortly. Instead of the Run Profile name, I'm going to add an extra field there that you can put a descriptive name in. You'll probably want these to be shorter, since they appear in the tab titles.

Since Cursive 1.9.0, the ns is actually shown in an overlay over the input pane, as you can see [here](https://cursive-ide.com/userguide/repl.html#using-the-repl).

**Comment by CmdrDats** [comment] 2019-12-06 10:56
awesome! good news :)

haha, I never noticed the ns in the input pane.. probably because it's off to the right - super useful, thanks :)

**Comment by cursive-ide** [comment] 2020-03-12 00:09
This is actually a dupe of #1974

**Closed by cursive-ide** 2020-03-12 00:09 UTC
