### ISSUE TITLE
IntelliJ 2016.2 stuck "scanning files to index"

### ISSUE THREAD

**Issue by akombo** [cursive-ide/cursive#1479] opened 2016-07-29 18:49 UTC
I don't recall making any significant configuration changes or any environmental changes outside of IntelliJ but the UI froze at one point and now when I try to restart I get stuck with an unresponsive UI and the only way to quit IntelliJ is to kill with the PID. This originally started with IntelliJ 15.0.6. My first attempt to fix this problem was to move a different `.IntelliJIdea15` directory from another workstation that was an earlier version. When that failed I tried installing the latest version of the IDE. Now that has failed as well and I am out of ideas (ha!).

Here is the idea.log:
[idea.log.txt](https://github.com/cursive-ide/cursive/files/391133/idea.log.txt)

Here is a recent thread dump:
[threadDump-20160729-134428.txt](https://github.com/cursive-ide/cursive/files/391137/threadDump-20160729-134428.txt)

I am going to open a Youtrack ticket as well. I believe this may be related to cursive since I saw cursive making calls near the bottom of a stacktrace.

**Comment by akombo** [comment] 2016-07-29 18:53
I forgot to mention the version of cursive being used. I try to update as soon as I am prompted but grepping the `.IntelliJIdea2016.2` directory yielded:

./.IntelliJIdea2016.2/config/plugins/clojure-plugin/lib/cursive-lein-shim-1.3.1-eap2-2016.2.jar
./.IntelliJIdea2016.2/config/plugins/clojure-plugin/lib/cursive-lein-bootstrap-1.3.1-eap2-2016.2.jar

This leads me to believe that I am using 1.3.1-eap2-2016.2.

Thanks,
Adam

**Comment by cursive-ide** [comment] 2016-07-29 22:09
Sorry you're having issues - these are normally caused by subtle bugs in the indexing, either Cursive's or IntelliJ's. Depending on how responsive your UI is, you have a couple of options:

The first is to open *Help&rarr;Enable Debug Log Categories*, add "#com.intellij.openapi.project.DumbServiceImpl" there, reproduce the issue and send me the log again. This is mostly useful to me to diagnose the issue, it won't actually help the problem, so feel free to skip it if you need to get work done. We might need to do this if the following steps don't work, since that will indicate a bug that's provoked by something in your project rather than just general funkiness.

The next thing to try is *File&rarr;Invalidate Caches* - hopefully that will sort out whatever the issue was if it's transient.

If your UI isn't responsive enough to do either of those, shut down IntelliJ and delete your `.IntelliJIdea2016.2/system` directory, which will do more or less the same thing.

Let me know how you get on!

**Comment by akombo** [comment] 2016-08-01 17:26
Thanks for getting back to me quickly. Unfortunately, the UI was completely frozen and I couldn't even interact with the IDE to exit the process. I had to kill it from the command line. After experimenting with upgrading the IDE and copying (scp) various versions of the .IntelliJIdea(15/2016.2) directory from other workstations I concluded that it was probably something project specific in the .idea directory. I started again with a clean version of IntelliJ 2016.2, imported settings through the import/export function provided by the IDE, and then recreated the project in question. This resolved my issue, but I did not have the wherewithal to save the .idea directory so I don't believe that I can recreate the problem. If this brings any investigation to a halt then I apologize and would understand if you'd like to close the issue.

Adam

**Comment by cursive-ide** [comment] 2016-08-01 22:48
Ok, that's no problem - I suspect it's a transient problem, so there's probably not much I could do about it anyway. I'll close this.

**Closed by cursive-ide** 2016-08-01 22:48 UTC

**Comment by baoxiehao** [comment] 2017-07-26 06:30
I came across the same problem, and all the solutions are not working. And lastly I found that I should setup the Project SDK for java. Referring https://plus.google.com/+JuhaLindfors/posts/XkwSHgVXNnQ

**Comment by lebedkin** [comment] 2017-10-05 20:38
same problem here, "Scanning files to index" never stops.

**Comment by baoxiehao** [comment] 2017-10-11 03:15
I tried to change the Java SDK from 6 to 8, and the scanning just stops... But later I came across it again. And now it is ok but I forget how is just works...

**Comment by ciroque** [comment] 2017-12-17 17:01
It appears it is using a polling technique instead of a FileWatcher / observer implementation. This isuper annoying in that the IDE freezes for milliseconds / seconds at a time and really affects my flow. Typed characters can take seconds to appear making it unclear if it is me, or the IDE.

Perhaps this is a function of running the IDE on Windows??
