### ISSUE TITLE
Add option to style current sexpr differently

### ISSUE THREAD

**Issue by cemerick** [cursive-ide/cursive#1635] opened 2017-01-13 15:44 UTC
via misha and dottedmag in slack, e.g.

![1_d1aftkwdk3kelsltrb0fog](https://cloud.githubusercontent.com/assets/47489/21935862/18b8e762-d97d-11e6-8c4e-fcb9a8777b56.png)

Discussed in the context of emacs here: https://blog.dottedmag.net/instant-highlighting-of-parentheses-in-emacs-bb060514a92

**Comment by cursive-ide** [comment] 2017-01-13 21:22
This looks like a dupe of #824. Nice idea to have it in bold rather than background colour though.

**Closed by cursive-ide** 2017-01-13 21:22 UTC
