### ISSUE TITLE
Allow macros to be defined as transparent

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1420] opened 2016-05-25 21:56 UTC
We use clairvoyant to trace our functions which has a macro `trace-forms`. It wraps around all of our code, and breaks Cursive's resolution. It would be nice if we could define that macro as 'transparent', so it doesn't affect resolution.

Relates to #979.

**Comment by cursive-ide** [comment] 2016-05-26 01:44
This is a dupe of #1417.

**Closed by cursive-ide** 2016-05-26 01:44 UTC
