### ISSUE TITLE
Jump to spec definition

### ISSUE THREAD

**Issue by wilkerlucio** [cursive-ide/cursive#1781] opened 2017-06-16 17:10 UTC
Add support to jump to spec definition. Currently the spec definition can be indexed from `(clojure.spec.alpha/def ::something)`. So when asked to jump into a qualified keyword cursive can jump to where the spec is defined.

**Comment by danielcompton** [comment] 2017-06-23 03:34
Dupe of #1549.

**Closed** 2017-06-23 21:49 UTC
