### ISSUE TITLE
Incorrect var/keyword highlight when prefix matches

### ISSUE THREAD

**Issue by rauhs** [cursive-ide/cursive#1413] opened 2016-05-23 09:37 UTC
Best explained with an example:

```
(let [{:keys [a/bar a/bar-x]} {}]
  bar-x
  :a/bar
  :a/bar-x)
```

Putting the cursor over `a/bar` also highlights `bar-x` and `a/bar-x`, even though it shouldn't. Same when putting the cursor over `:a/bar`.

**Comment by cursive-ide** [comment] 2016-06-13 04:41
This is a duplicate of #800.

**Closed by cursive-ide** 2016-06-13 04:41 UTC
