### ISSUE TITLE
Error generating stubs for module ...: Exception in thread "main"

### ISSUE THREAD

**Issue by biggert** [cursive-ide/cursive#1524] opened 2016-09-08 20:09 UTC
Whenever I attempt to generate stubs in my project, I get the exception below. I'm not sure what else to provide to help you out. It got shown in a balloon which doesn't let me scroll so I captured as much as I could.

> Exception in thread "main"
> java.io.FileNotFoundException: Could not locate cljs/closure__init.class or cljs/closure.clj on classpath., compiling:(/private/var/folders/bg/g18d52c5195bzbyqfkp7rzzr0000gn/T/create-stub1584662057828817889.clj:2:1)
> at clojure.lang.Compiler.load(Compiler.java:7391)
> at clojure.lang.Compiler.loadFile(Compiler.java:7317)
> at clojure.lang.RT$3.invoke(RT.java:320)
> at user$eval5.invokeStatic(form-init1357032189371343701.clj:1)
> at user$eval5.invoke(form-init1357032189371343701.clj:1)
> at clojure.lang.Compiler.eval(Compiler.java:6927)
> at clojure.lang.Compiler.eval(Compiler.java:6917)
> at clojure.lang.Compiler.load(Compiler.java:7379)
> at clojure.lang.Compiler.loadFile(Compiler.java:7317)
> at clojure.main$load_script.invokeStatic(main.clj:275)
> at clojure.main$init_opt.invokeStatic(main.clj:277)
> at clojure.main$init_opt.invoke(main.clj:277)
> at clojure.main$initialize.invokeStatic(main.clj:308)
> at clojure.main$null_opt.invokeStatic(main.clj:342)
> at clojure.main$null_opt.invoke(main.clj:339)
> at clojure.main$main.invokeStatic(main.clj:421)
> at clojure.main$main.doInvoke(main.clj:384)
> at clojure.lang.RestFn.invoke(RestFn.java:421)
> at clojure.lang.Var.invoke(Var.java:383)
> at clojure.lang.AFn.applyToHelper(AFn.java:156)
> at clojure.lang.Var.applyTo(Var.java:700)
> at clojure.main.main(main.java:37)
> Caused by: java.io.FileNotFoundException: Could not locate cljs/closure__init.class or cljs/closure.clj on classpath.
> at clojure.lang.RT.load(RT.java:456)
> at clojure.lang.RT.load(RT.java:419)
> at clojure.core$load$fn__5677.invoke(core.clj:5893)
> at clojure.core$load.invokeStatic(core.clj:5892)
> at clojure.core$load.doInvoke(core.clj:5876)
> at clojure.lang.RestFn.invoke(RestFn.java:408)
> 
> at clojure.core$load_one.invokeStatic(core.clj:5697)
> at clojure.core$load_one.invoke(core.clj:5692)
> at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
> at clojure.core$load_lib.invokeStatic(core.clj:5736)
> at clojure.core$load_lib.doInvoke(core.clj:5717)
> at clojure.lang.RestFn.applyTo(RestFn.java:142)
> at clojure.core$apply.invokeStatic(core.clj:648)
> at clojure.core$load_libs.invokeStatic(core.clj:5774)
> at clojure.core$load_libs.doInvoke(core.clj:5758)
> at clojure.lang.RestFn.applyTo(RestFn.java:137)
> at clojure.core$apply.invokeStatic(core.clj:648)
> at clojure.core$require.invokeStatic(core.clj:5796)
> at clojure.core$require.doInvoke(core.clj:5796)
> at clojure.lang.RestFn.invoke(RestFn.java:512)
> at user$eval54.invokeStatic(create-stub1584662057828817889.clj:2)
> at

**Comment by cursive-ide** [comment] 2016-09-08 22:12
What that looks like is that you have a CLJS project (probably using Om or Om Tools) which doesn't have ClojureScript itself on the classpath? Is that possible?

**Comment by biggert** [comment] 2016-09-08 23:47
That is correct. Is there something I need to do special to get the stubs generated (or at a minimum hide the message that tells me to do it)?

**Comment by cursive-ide** [comment] 2016-09-08 23:49
Can you explain why your project is like this? Surely the application doesn't actually work? Just trying to get some ideas for possible suggestions.

**Comment by biggert** [comment] 2016-09-09 02:29
I should read the full question before answering. It is both CLJS and CLJ using profiles defined in the project.clj to differentiate.

**Comment by cursive-ide** [comment] 2016-09-09 05:52
Ah, ok. So the problem is likely that the stub generation does not currently use the profiles selected in the lein toolwindow. That is fixed in the next build so I'll mark this closed for now. If the problem still occurs after the next EAP feel free to re-open.

**Closed by cursive-ide** 2016-09-09 05:52 UTC
