### ISSUE TITLE
Leiningen "Unused global declaration '-main'"

### ISSUE THREAD

**Issue by perryprog** [cursive-ide/cursive#1519] opened 2016-09-04 16:51 UTC
When in a Leiningen project, the `core.clj` file has the `-main` function. However, Cursive thinks that because no file ever calls it, it isn't used. Perhaps is any `-main` function is in the file `core.clj` it won't report it.

**Comment by cursive-ide** [comment] 2016-09-06 08:38
Dupe of #631.

**Closed by cursive-ide** 2016-09-06 08:38 UTC
