### ISSUE TITLE
Explain why Java interop cannot be resolved

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#946] opened 2015-07-03 01:12 UTC
I'm finding that a lot of reflection issues also fail to be resolved by Cursive. It could be handy to see all of the possible methods that are being overloaded when you look at the docs/tooltip for an item.

![screenshot of intellij idea 3-07-15 1 06 24 pm](https://cloud.githubusercontent.com/assets/811954/8490874/53fa7938-2184-11e5-833f-99c1ac23b81a.png)

If you showed all of the signatures for an overloaded method this would make it a lot easier to see which one it is likely to be.

**Comment by cursiveclojure** [comment] 2015-07-03 08:26
So I actually tried that, the issue is that the tooltip is huge. One thing I'll do when the inference stabilises is have quickfixes suggesting type hints for the various params.

**Comment by cursiveclojure** [comment] 2015-07-03 08:27
Oh, and one thing - Show Parameter info should work for this, it will show all matching methods.

**Comment by danielcompton** [comment] 2015-07-04 08:24
Yep, didn't think to try Show Parameter info because I assumed it couldn't resolve it. It works well!

**Comment by cursive-ide** [comment] 2024-02-10 00:47
Closing this, since it was fixed a long time ago.

**Closed by cursive-ide** 2024-02-10 00:47 UTC
