### ISSUE TITLE
Figwheel sidecar doesn't pick changes in cljs files when running it with Cursive REPL

### ISSUE THREAD

**Issue by visibletrap** [cursive-ide/cursive#1710] opened 2017-04-13 01:12 UTC
### Copied from slack

I have cljs files under `src/cljs` and I config dev output to be at `resources/public/out`. But when I start local cursive repl or connect cursive to lein repl, these things happen.
1. When I modify file under `src/cljs`, Figwheel doesn’t update some (a few) files under `resources/public/out` as usual.
2. When I modify a problematic file, it looks like Figwheel know that the file is modified. It tries to recompile and push that file to browser. There’s a recompilation messages appear in log and update sign show up on browser. But that modification doesn’t show up on the browser, even after hard refresh.
3. I noticed that the problematic files appear under `target/classes` path. If I remove these files, the issue is fixed and figwheel is back to work as usual.
4. The problematics files are always the same files
5. Things above don’t happen when I use `cider-jack-in` or `cider-connect`

**Comment by visibletrap** [comment] 2017-04-13 01:12
@cursive-ide 's reply
> The only thing I can think of is that Cursive is copying those files there as part of a compile process, and that Figwheel for some reason ignores changes to files that it also finds under the compile output path.

> How do you run your REPL?

**Comment by visibletrap** [comment] 2017-04-13 01:17
The issue occur for both ways
- Curisve Local REPL > “Run nREPL with Leiningen”. No other configurations.
- `lein repl` in macOS’s termianal. Then Remote REPL > “Use Leiningen REPL port”

**Comment by visibletrap** [comment] 2017-04-13 01:24
It seems to me that it’s normal behavior for cursive to copy cljs files to `target/classes` but figwheel should just not care about those files

**Comment by cursive-ide** [comment] 2017-04-13 02:19
In your run configs, do you have "Build" in your "Before Launch" section near the bottom of your run config? If so, does removing that help? That's the only time that I think Cursive would copy those files to the output dir.

**Comment by visibletrap** [comment] 2017-04-13 12:44
Yes, removing that helps. The files are not copied over and figwheel works normally.

- What's is the downside of removing that?
- Is copying cljs files over an expected behavior? 

The issue seems to happen only for figwheel sidecar. It doesn't happen for `lein-cljsbuild` or `lein-figwheel`. I may dig into sidecar and send in a patch later.

If you think copying cljs files over is an expected behavior, I'll close this issue.

**Comment by cursive-ide** [comment] 2017-04-13 23:00
Well, for some value of "expected", yes :-). IntelliJ will copy resource files to the output on compile so that they're included in any build artifacts produced. The ideal solution would be for that Build action not to be added to Clojure run configs by default, but for boring internal reasons that's quite hard. I'm planning to go back and try again sometime soon.

I can't think of any downsides of removing that right now.

I asked @bhauman about this, and he replied:

> The is no code that does that expressly but … the cljs compiler resolves source files from the classpath.  So if the cljs file `src/example/core.cljs` is also found at `target/classes/example/core.cljs` you may have a classpath masking situation on your hands with stale assets and such

So what might have been happening is that Figwheel detected the files had changed since it's watching the directory on the FS, but then when it goes to compile it gets the old version from the `target/classes` path.

It's not a bug as such, and since there's a decent workaround I'll close this. I'm going to try to make a better fix in the future.

**Closed by cursive-ide** 2017-04-13 23:00 UTC

**Comment by visibletrap** [comment] 2017-04-14 02:48
Got it. Thanks for help figuring this out, Colin.
