### ISSUE TITLE
With Idea 2020.1 Run leading to error

### ISSUE THREAD

**Issue by dkovalkov** [cursive-ide/cursive#2350] opened 2020-04-11 13:09 UTC
Like this https://www.dropbox.com/s/rt26c19wgcphb7r/Screenshot%202020-04-11%2016.05.15.png?dl=0

**Comment by cursive-ide** [comment] 2020-04-13 11:04
There are more reports of this error here: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360007951959-Error-Running-Leiningen

**Comment by markbastian** [comment] 2020-04-13 13:47
This is happening for me, too. This happens on OS X, Lein 2.9.3, IJ 2020.1. It can be reproduced by running any of the lein tasks from the Leiningen panel. The REPL works fine and you can still run lein tasks from the terminal.

**Comment by brown131** [comment] 2020-04-13 14:17
This is happening for me as well. 

Cusrive 1.9.1-2020.1
Leiningen 2.9.3
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3

This has also been reported by others on the IntelliJ Support site: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360007951959-Error-Running-Leiningen?flash_digest=5984cd31f5dfe564ee14f1cddb682fdf88cdd930

**Comment by Jheschl17** [comment] 2020-04-13 14:25
Same problem here

Cursive 1.9.1-2020.1
Leiningen 2.9.3
IntelliJ IDEA Ultimate 2020.1
OpenJDK 14
Linux Mint Cinnamon 19.3 kernel 5.3.0-46-generic

Error message:
```
Error running 'new-project.core (1)': failed to access class com.intellij.execution.impl.ProcessStreamsSynchronizer from class com.intellij.execution.impl.ConsoleViewRunningState (com.intellij.execution.impl.ProcessStreamsSynchronizer is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @402f32ff; com.intellij.execution.impl.ConsoleViewRunningState is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @c9a79eb)
```

**Comment by AylanBoscarino** [comment] 2020-04-15 11:35
Facing the same problem.

**Comment by Icaruspooky** [comment] 2020-04-15 12:56
Same issue here.

**Comment by Icaruspooky** [comment] 2020-04-15 13:01
Same issue here.
Cursive 1.9.1-2020.1
Intellij 2020.1 Ultimate
leiningen 2.9.3-1

**Comment by Icaruspooky** [comment] 2020-04-15 15:46
Another report here:
https://stackoverflow.com/questions/61189732/can-not-run-clojure-project-with-cursive-using-leiningen

**Comment by vidalvasconcelos** [comment] 2020-04-25 02:00
I had this problem yesterday and today I can upgrade the plugin and resolve this problem. Thank you very much for support.

**Comment by asuresh-quinnox** [comment] 2020-04-30 15:36
Hi,
I am facing the issue below even after installing the new cursive plugin, which says is built from 1.9.2-eap1

I have below

D:\Clojure\myExamples\tutorial>lein -version
Leiningen 2.9.3 on Java 11.0.6 OpenJDK 64-Bit Server VM

D:\Clojure\myExamples\tutorial>java -version
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10-LTS, mixed mode)

Error Snip

Error running 'leinrun': failed to access class com.intellij.execution.impl.ProcessStreamsSynchronizer from class com.intellij.execution.impl.ConsoleViewRunningState (com.intellij.execution.impl.ProcessStreamsSynchronizer is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @7a46a697; com.intellij.execution.impl.ConsoleViewRunningState is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @5e2cb488)

**Comment by asuresh-quinnox** [comment] 2020-04-30 16:29
It is working after, uninstalling and installing the community edition ideaIC-2020.1.
this time during the fresh cursive-ide it installed the above said version and works fine

**Comment by hareeshkavumkulath** [comment] 2020-05-19 06:22
It is working after updating the plugin. Go to settings -> plugin -> installed plugins -> cursive -> update.

**Comment by jefimm** [comment] 2020-05-24 13:56
still does not work with  1.9.2-eap4 on OSX 
Idea 2020.1.1 Ultimate

**Comment by hareeshkavumkulath** [comment] 2020-05-24 16:41
> still does not work with 1.9.2-eap4 on OSX
> Idea 2020.1.1 Ultimate

The version which worked for me is 1.9.2-eap3-2020.1 with the community edition. 
I have 1.9.2-eap4 with Ultimate, which is not working.

**Comment by soulchips** [comment] 2020-05-25 18:30
> > still does not work with 1.9.2-eap4 on OSX
> > Idea 2020.1.1 Ultimate
> 
> The version which worked for me is 1.9.2-eap3-2020.1 with the community edition.
> I have 1.9.2-eap4 with Ultimate, which is not working.

Was having the same issue. This resolved it for me.

**Comment by rasheeddavid** [comment] 2020-06-01 07:11
This issue was closed but there is no working solution to this any where on the internet.. kilode?

**Comment by cursive-ide** [comment] 2020-06-01 09:17
I'm going to reopen this. Can everyone who is still experiencing the issue let me know the following:
1. Cursive and IntelliJ versions.
2. What you're actually doing to reproduce the issue - running leiningen run configs? Running REPLs? Something else? Any details about what is still causing this would be very useful.

**Comment by jefimm** [comment] 2020-06-01 09:19
still does not work with 1.9.2-eap4 on OSX
Idea 2020.1.1 Ultimate
attempt to debug code

**Comment by cursive-ide** [comment] 2020-06-01 09:28
@jefimm Thanks for that. When you're trying to debug, what sort of run configuration are you using? A REPL or a script? Can you send some details, or a screenshot of the run config?

**Comment by jefimm** [comment] 2020-06-01 09:31
just selecting the midje test and pressing the debug button

**Comment by cursive-ide** [comment] 2020-06-01 09:34
@jefimm Can you send a screenshot of what you're doing please? Cursive doesn't support midje, so I'm not sure how you're trying to run this. If you'd rather not make the screenshot public you can send it to cursive@cursive-ide.com.

**Comment by jefimm** [comment] 2020-06-01 10:07
sent to cursive@cursive-ide.com

**Comment by soverysour** [comment] 2020-06-01 11:54
FWIW, enabling EAP builds in IntelliJ and updating, restarting intellij fixed this for me. I am on 2020.1, and "it didn't work" for me, meaning that I couldn't even click on the green arrow next to `-main` to run it, without getting that big mean red error.

So, go to `File - Settings`, then `Languages & Frameworks - Clojure`, enable `Check for EAP builds`,  then go to `Help - Check for Updates`, and you should get to update the plugin.

The `Cursive` version that I got installed is `1.9.2-eap5-2020.1`.

**Comment by asuresh-quinnox** [comment] 2020-06-01 12:04
![to-group](https://user-images.githubusercontent.com/63102865/83407284-4e629a80-a408-11ea-8f02-f28c1be58146.png)

**Comment by Jheschl17** [comment] 2020-06-01 12:10
1. tried with both [Intellij Ultimate 2020.1.1](https://pastebin.com/G28sYW1y) and [Intellij Community 2020.1.1](https://pastebin.com/V3wmewLy) on Manjaro Linux 20.0.1 with kernel 5.6.15-1. Cursive 1.9.1-2020.1
2. open Intellij -> Create New Project -> Clojure -> Leiningen -> Next -> Finish -> Right Click core.clj -> Run -> `13:59	Error running 'untitled.core': failed to access class com.intellij.execution.impl.ProcessStreamsSynchronizer from class com.intellij.execution.impl.ConsoleViewRunningState (com.intellij.execution.impl.ProcessStreamsSynchronizer is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @402f32ff; com.intellij.execution.impl.ConsoleViewRunningState is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @7693e4f3)`

**Comment by cursive-ide** [comment] 2020-06-02 01:36
@Jheschl17 Yes, this fix is still only in EAP builds, see [here](https://cursive-ide.com/userguide/index.html#eap) for how to install those.

**Comment by trennble** [comment] 2020-06-05 06:52
does not work with 1.9.2-eap5 on Window10
Idea 2020.1.1 Ultimate
attempt to run `clojure Application`

**it work after I uninstall cursive plugin and re-install it**

**Comment by dknesek** [comment] 2020-06-06 15:32
Is there any freshly installed combination of Intellij Community and this plugin that works? The trial-and-error of reinstalling different combinations is maddening.

**Comment by thiagozg** [comment] 2020-06-07 18:11
> FWIW, enabling EAP builds in IntelliJ and updating, restarting intellij fixed this for me. I am on 2020.1, and "it didn't work" for me, meaning that I couldn't even click on the green arrow next to `-main` to run it, without getting that big mean red error.
> 
> So, go to `File - Settings`, then `Languages & Frameworks - Clojure`, enable `Check for EAP builds`, then go to `Help - Check for Updates`, and you should get to update the plugin.
> 
> The `Cursive` version that I got installed is `1.9.2-eap5-2020.1`.

Worked for me, thanks!

**Comment by gadfly361** [comment] 2020-06-08 05:01
@cursive-ide I was experiencing this issue (using `Run -main from Clojure namespace`) and upgrading to the EAP of cursive fixed the problem :+1:

Currently using:
- Idea 2020.1.2 Ultimate
- macOS 10.15.5
- cursive 1.9.2-eap5-2020.1

**Comment by akessner** [comment] 2020-06-12 13:41
I'm running 
IntelliJ IDEA 2020.1.2 (Community Edition)
Build #IC-201.7846.76, built on June 1, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1488M
Cores: 4
Non-Bundled Plugins: com.cursiveclojure.cursive, com.intellij.plugins.watcher, org.jetbrains.kotlin
cursive 1.9.2-eap6

I'm trying to learn closure, using scip.
Wrote a test and hit the green arrow button and I get this error.

**Comment by markjamesm** [comment] 2020-06-19 03:40
I'm running into this issue on:

- Windows 10.0.18363 Build 18363
- Idea 2020.1.2 Ultimate
- Cursive 1.9.1-2020.1

Things had been working fine until I tried running the REPL after making some code changes and received the following message:

@Jheschl17 's solution solved the issue for me.

**Comment by kiryushinsa** [comment] 2020-06-26 14:47
Same problem with:

Cursive - 1.9.1-2020.1
Windows - Version 10.0.18362 build 18362
Idea 2020.1.2 Ultimate

**Comment by victorhbetoni** [comment] 2020-07-01 20:19
> 
> 
> FWIW, enabling EAP builds in IntelliJ and updating, restarting intellij fixed this for me. I am on 2020.1, and "it didn't work" for me, meaning that I couldn't even click on the green arrow next to `-main` to run it, without getting that big mean red error.
> 
> So, go to `File - Settings`, then `Languages & Frameworks - Clojure`, enable `Check for EAP builds`, then go to `Help - Check for Updates`, and you should get to update the plugin.
> 
> The `Cursive` version that I got installed is `1.9.2-eap5-2020.1`.

Worked for me too!

**Comment by cursive-ide** [comment] 2020-07-27 08:50
Since there seemed to be some confusion about the required versions here - is anyone still experiencing this problem with 1.9.2 or 1.9.3-eap1? @jefimm?

**Comment by cursive-ide** [comment] 2020-08-03 03:33
I'm going to close this issue again. If anyone is still receiving this with a Cursive version greater or equal to 1.9.2, please open a new issue for it.

**Closed by cursive-ide** 2020-08-03 03:33 UTC
