### ISSUE TITLE
IDEA Community edition hangs on startup immediately after installing Cursive

### ISSUE THREAD

**Issue by grahen** [cursive-ide/cursive#1735] opened 2017-05-02 08:25 UTC
Installed the newest version of Intellij Idea Community edition and immediately after that installed Cursive from the plugin repo. Tried to restart the IDEA, then during startup it hanged. 

Removed the plugin from the plugins directory and then it starts again. 
[threads.tar.gz](https://github.com/cursive-ide/cursive/files/969853/threads.tar.gz)

**Comment by yugensoft** [comment] 2017-05-08 16:35
Yeah same problem with normal edition:
https://github.com/cursive-ide/cursive/issues/1726

This plugin seems out of control, pages of issues with no comments. Perhaps indicates room for competitors in this space?

**Comment by cursive-ide** [comment] 2017-05-09 04:38
I believe this is a duplicate of #1702, which is fixed in 1.5.0, the latest stable build of Cursive.

**Closed by cursive-ide** 2017-05-09 04:38 UTC
