### ISSUE TITLE
Bad spacing in 'Edit REPL Commands' window

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1625] opened 2017-01-04 03:46 UTC
<img width="585" alt="screenshot of intellij idea 4-01-17 4-45-31 pm" src="https://cloud.githubusercontent.com/assets/811954/21631183/47595cc8-d29d-11e6-8c45-675b6cfe0c34.png">

**Comment by cursive-ide** [comment] 2023-01-26 04:40
This is pretty old and I can't reproduce, so I'm going to close it. Let me know if this is still an issue.

**Closed by cursive-ide** 2023-01-26 04:40 UTC
Labels: REPL
