### ISSUE TITLE
No auto-pairing of closing parens, brackets, etc. in scratch buffers

### ISSUE THREAD

**Issue by cap10morgan** [cursive-ide/cursive#1969] opened 2018-04-04 16:27 UTC
Using IDEA 2018.1 and Cursive 1.7.0-eap1-2018.1 in parinfer mode.

Steps to reproduce:

1. Open a new Clojure scratch buffer
1. Type `(`

Expected behavior:

Cursive automatically inserts the closing `)` after the cursor.

Observed behavior:

No closing `)` is inserted.

Same behavior for `[`, `]`, `{`, and `}` too.

**Comment by cursive-ide** [comment] 2020-11-23 03:02
I can't reproduce this any more, I think this must have been fixed by some underlying scratch file fixes. If anyone is still experiencing this, let me know and I'll re-open it.

**Closed by cursive-ide** 2020-11-23 03:02 UTC
