### ISSUE TITLE
alias marked as unused but it is used

### ISSUE THREAD

**Issue by ghost** [cursive-ide/cursive#638] opened 2014-11-18 18:31 UTC
```
(ns renderer.renderer
    (:require
        [om.dom :as dom]   -> dom is marked as unused
        [om.core :as om :include-macros true]
        [goog.string :as gstring]
        [goog.string.format]
        [ajax.core :refer [GET POST]]
        [secretary.core :as secretary]
        [markdown.core :refer [md->html]]
        [renderer.helper :as h]))
.......
(defmethod render-page :demo [{:keys [title component language name origin explanation]}]
    (dom/div nil
             (dom/div #js{:className class-title} title)
       ..........
```

**Comment by mfikes** [comment] 2015-01-03 05:50
@danielcompton has a good point. I also encountered this, but interestingly it only affects CLJS:

http-kit employs a [function-defining macro](https://github.com/http-kit/http-kit/blob/master/src/org/httpkit/client.clj#L187) and I was replicating this API into ClojureScript and discovered the same issue.

I created a minimal [reduction repo](https://github.com/mfikes/cursive-resolve) that demonstrates this.

If you pull down that repo and open it in Cursive, you'll see a problem with [one of the aliases](https://github.com/mfikes/cursive-resolve/blob/master/src/cljs/alpha/beta.cljs#L2) where the same doesn't occur [for an analogous use](https://github.com/mfikes/cursive-resolve/blob/master/src/clj/gamma/delta.clj#L2) from Clojure.

**Comment by cursiveclojure** [comment] 2015-01-05 12:13
Interesting, thanks for the reproduction case, I'll take a look at this.

**Comment by cursiveclojure** [comment] 2015-02-06 08:39
I actually didn't expect this to be a problem - @danielcompton is correct that the dom functions are generated from macros but that shouldn't cause the alias to be unresolved, and indeed this works correctly in Clojure. However this is more complicated in ClojureScript. In Clojure, an alias is unambiguous - it only has a single possible resolution. However in ClojureScript it can have two - it might be an alias for Clojure macros, or it might be an alias for ClojureScript. When resolving I can't tell which is which, so I also look at the qualified symbol to see what it actually resolves to, and then use that to choose the correct alias. However this breaks when the qualified symbol doesn't resolve, as in the case of symbols defined from macros.

I'll see if I can make the inspection more robust to this case. This specific case is fixed in the upcoming build, since Cursive now resolves the om and om-tools DOM methods correctly.

**Comment by Sardtok** [comment] 2022-02-24 14:03
Unsure if this is the same issue, but I Cursive marks gstring as unused for me as well. Similar import as above. This is unfortunate with the new Optimize imports functionality, which ends up removing the namespace, although functions in the namespace are called.

**Comment by cursive-ide** [comment] 2022-02-25 03:03
@Sardtok When you use gstring, do the calls get marked with an unresolved warning?

**Comment by Sardtok** [comment] 2022-02-25 09:18
![RequireGoogString](https://user-images.githubusercontent.com/613667/155688791-920245ea-63f8-44d9-aae6-eefe8fb3a3be.png)

No warning on usage, and auto complete also works fine.

**Comment by Sardtok** [comment] 2022-02-25 09:29
Tried aliasing other Google Closure namespaces and I get the same results. `[goog.net :as net]` and then referencing `net/XhrIO`, gives auto-complete for functions in the namespace, and no warning on usage, but marks the alias as unused in the require vector.

**Comment by cursive-ide** [comment] 2022-02-25 19:23
@Sardtok Thanks, I'll investigate.

**Comment by cursive-ide** [comment] 2022-03-15 04:38
@Sardtok's issue is fixed in the next EAP build, and the original issue looks like it was fixed a long time ago.

**Closed** 2022-04-13 00:46 UTC
Labels: Macros
