### ISSUE TITLE
High CPU / input lag - performance issues with 1.5.0-eap3-17-gd29f45b?

### ISSUE THREAD

**Issue by gnl** [cursive-ide/cursive#1685] opened 2017-03-15 07:32 UTC
Can't really narrow it down much further than this, but since the upgrade to 1.5.0-eap3 I've been experiencing some performance issues often severely affecting input lag - I'd be happy to provide additional data / troubleshoot if required.

**Comment by thheller** [comment] 2017-04-08 16:42
I upgraded to EAP4 recently (no EAP before) and performance has definitely taken a big hit. I can easily max out my CPU by just coding normally in a file.

These files are very bad:
https://github.com/thheller/shadow-build/blob/master/src/main/shadow/cljs/build.clj
https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/analyzer.cljc
https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/compiler.cljc

They are all pretty big files but the input lag wasn't this bad before.

I did a bit of sample profiling with JVisualVM and this looks suspicious:

![idea-hotspot](https://cloud.githubusercontent.com/assets/144930/24830669/c59fe82c-1c8a-11e7-8d3a-5f3d1b2174b2.png)

You can get the full JVisualVM report here:
http://zilence.net/cursive/idea-hotspot.nps

I have no nREPL running so it must be something from Cursive.

**Comment by cursive-ide** [comment] 2017-04-09 10:04
@thheller Does File->Invalidate caches and restart... help that? It looks like a lot of the time is in the BaseDataReader/Writer, which are the indexing classes.

**Comment by thheller** [comment] 2017-04-09 10:40
@cursive-ide no it does not make a difference. After invalidating and waiting for the re-index to settle down I get the same CPU-heavy behaviour. The input lag does seem to get worse over time though.

I did a bunch of cleanup/refactor work recently which involved moving a few`defn` around, initially this works ok but after a while I have so sometimes wait a few seconds for Idea to recover before I can type again.

**Comment by cursive-ide** [comment] 2017-04-09 22:01
Could either (or both) of you capture a CPU snapshot as detailed [here](https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems)? I'll take a look and see if I can see anything.

Also, if you look at the memory indicator (turned on using *Settings→Appearance & Behavior→Appearance→Show memory indicator*) do you see a lot of memory churn?

**Comment by thheller** [comment] 2017-04-10 07:53
I have
```
# custom IntelliJ IDEA VM options

-Xms128m
-Xmx750m
-XX:ReservedCodeCacheSize=240m
-XX:+UseCompressedOops
-agentlib:yjpagent=delay=10000,probe_disable=*
```
in `~/Library/Preferences/IdeaIC2017.1/idea.vmoptions` but I cannot start IDEA anymore.

All I get is when trying to launch via `open`, everything else just fails without any msg:
```
LSOpenURLsWithRole() failed with error -10810 for the file /Users/zilence/Downloads/IntelliJ IDEA CE.app.
```

**Comment by thheller** [comment] 2017-04-10 08:04
```
2017-04-10 10:04:23.610 idea[22295:21066848] allVms required 1.8*,1.8+
2017-04-10 10:04:23.613 idea[22295:21066857] fullFileName is: /Applications/IntelliJ IDEA CE.app/Contents/bin/idea.vmoptions
2017-04-10 10:04:23.613 idea[22295:21066857] fullFileName exists: /Applications/IntelliJ IDEA CE.app/Contents/bin/idea.vmoptions
2017-04-10 10:04:23.613 idea[22295:21066857] Value of IDEA_VM_OPTIONS is (null)
2017-04-10 10:04:23.613 idea[22295:21066857] Processing VMOptions file at /Users/zilence/Library/Preferences/IdeaIC2017.1/idea.vmoptions
2017-04-10 10:04:23.613 idea[22295:21066857] Done
Error occurred during initialization of VM
Could not find agent library yjpagent on the library path, with error: dlopen(libyjpagent.dylib, 1): image not found```

**Comment by cursive-ide** [comment] 2017-04-11 00:35
Assuming you're on the community edition, there's a section in the doc about that:

> IntelliJ IDEA and PyCharm Community Editions do not include a YourKit profiler agent, because the YourKit agent library is not open-source. To take a CPU or memory snapshot with the Community Edition, you can download an evaluation version of YourKit Java Profiler, copy the yjpagent library to the IDE bin directory, add it to the .vmoptions as described above, and connect to the running IDE instance from the standalone YourKit Profiler UI.

Sorry, it's a bit more messing around. The other option would be to download an evaluation of IntelliJ Ultimate edition and use that to produce the dump. I'll try to reproduce it here too.

**Comment by thheller** [comment] 2017-04-11 06:42
Maybe this helps: http://zilence.net/cursive/cursive-flight-recorder.jfr

It is a recording for Java Mission Control (`jmc`) which is slightly better than the JVisualVM recording. Switched to the Oracle JDK for this which made IDEA pretty ugly. Didn't do a whole lot of actual work with this. The recording is from me just typing random stuff into the source files at different locations (`let`, `defn`, ...). As you can see it easily eats 40% CPU of my machine (MacBook Pro (Retina, 15-inch, Mid 2015), 2,5 GHz Intel Core i7, 16 GB).

The input lag however only gets worse in certain situations it seems. Refactoring a variable name is definitely one case, `#_` comments seem to have an effect to.

I'll look into yourkit, I had some evaluation licenses over the years. I might not get another.

**Comment by cursive-ide** [comment] 2017-04-11 07:43
Ok, thanks - I've been meaning to investigate Flight Recorder, so this is a great excuse. I'll see if I can reproduce, but often with these sorts of problems it's hard without having actual work to do in the relevant files.

**Comment by thheller** [comment] 2017-04-11 10:14
Excuse the stack image but something I noticed is that editing anything inside `#js [foo]` seems to cause huge lag. Even just deleting the thing via backspace.

Maybe there is a clue in there.

![huge-index-stack](https://cloud.githubusercontent.com/assets/144930/24904316/6321a3ca-1eb0-11e7-8141-2cc4c6906f69.png)

**Comment by cursive-ide** [comment] 2017-04-12 00:42
@gnl BTW from which version did you upgrade to eap3? The previous EAP, or a stable version?

**Comment by gnl** [comment] 2017-04-13 15:41
Sorry about the delay, been a busy few days. Here's the snapshot:

[IU-171.4073.35_gnl_13.04.2017_18.35.39.zip](https://github.com/cursive-ide/cursive/files/920128/IU-171.4073.35_gnl_13.04.2017_18.35.39.zip)

It's from eap6 and I'm doing some inline rename refactoring and then normally typing - the excessive input lag occurs during the refactoring. I wasn't able to reproduce the original behaviour that prompted me to open the issue, which was excessive input lag during normal typing.

I wasn't able to reproduce before upgrading Cursive either (with eap3) and I've been on the EAP channel for a while now.

I'll keep an eye on the memory, but so far I can't see anything excessive, it's moving between ~150 and ~220 out of 1484MB.

**Comment by gnl** [comment] 2017-04-14 00:15
After a couple hours of writing ClojureScript the memory indicator shows 1210 of 1484M, after having closed the REPL and all panes, if that's somehow relevant.

**Comment by cursive-ide** [comment] 2017-04-14 10:59
@gnl If you click the memory indicator to provoke a GC, does that free it?

**Comment by gnl** [comment] 2017-04-15 07:01
Didn't manage to get back to 1200MB, reached ~800M during the last session. On clicking the memory indicator it was released and went down to ~200M, but then quickly went back to 4-500 while just moving the cursor around the document.

**Comment by cursive-ide** [comment] 2017-04-15 08:29
That's ok though - the churn is higher than I'd like, but if it drops back to 200M then a memory leak isn't the main issue.

**Comment by gnl** [comment] 2017-04-16 04:16
Just now I experienced noticeably high input lag during normal typing and even higher when holding down backspace for example. I captured a new CPU snapshot:

[IU-171.4073.35_gnl_16.04.2017_07.12.19.zip](https://github.com/cursive-ide/cursive/files/924083/IU-171.4073.35_gnl_16.04.2017_07.12.19.zip)

**Comment by gnl** [comment] 2017-04-16 04:23
And another one from excessive input lag during a small local inline rename refactoring of the `fn-name-replacement` binding in the following code:

```
        test-defn         (let [testfn-name         (symbol (str fun-name test-fn-suffix))
                                fn-name-replacement {fun-name testfn-name}]
                            (->> (list fn-deftype testfn-name docstring args prepost body)
                                 (remove nil?)
                                 (walk/prewalk fn-name-replacement)))
```

[IU-171.4073.35_gnl_16.04.2017_07.19.05.zip](https://github.com/cursive-ide/cursive/files/924085/IU-171.4073.35_gnl_16.04.2017_07.19.05.zip)

**Comment by gnl** [comment] 2017-04-16 07:13
Something just occurred to me - is it possible that under certain conditions something like inspection, highlighting etc., is triggered immediately on every keystroke rather than after a brief timeout and that there's been a change in this behaviour?

**Comment by cursive-ide** [comment] 2017-04-17 04:21
@gnl Thanks for the dumps, I'll take a look at them tomorrow.

What you suggest is possible, but unlikely - that would have been a fairly major change at the IntelliJ level, not in Cursive. I suspect a more likely problem is Cursive holding on to a read lock during some operations for too long, so the Swing EDT gets blocked waiting for a write lock which affects UI responsiveness. I can't remember if the CPU dumps contain thread contention information, I'll check that tomorrow.

**Comment by cursive-ide** [comment] 2017-04-18 00:41
@gnl So actually, your hunch was correct - at least, something similar. What I can't figure out is why this would suddenly have started happening, because the relevant code has not changed for ages. It's also caused by an interaction with IdeaVim, so possibly IdeaVim has changed in some way recently? I'm not sure.

Anyway, I've disabled the offending functionality in Cursive. I believe this should fix your issue, and from some testing it seems that perhaps it's no longer required any more. I'm not sure why - I'm checking with JetBrains. If this doesn't fix your issue, feel free to re-open this.

**Comment by gnl** [comment] 2017-04-18 05:09
It does look a bit better now (I had eap4 before), but I'm not 100% sure I'm not imagining it, as it's not a great difference.

I looked into it a bit more on the user side and I believe I was able to narrow it down somewhat. I tested with and without IdeaVIM, 1.5.0-eap7, eap1 and 1.4.3 with IDEA 2017.1 (I did invalidate caches/restart between downgrades):

* IdeaVIM plugin on/off doesn't make a difference
* The older versions (eap1 and older) had even worse input lag when inline refactoring (however the issues aren't limited to inline refactoring, it's just what I used to reproduce them)
* What does make a big difference is file type and size:
** large .cljc file (~1100 LOC) with lots of macros and reader conditionals - high input lag, even when doing something completely local to one small function/macro
** large .cljs file (~800 LOC) - much better, but still clearly noticeable)
** small .cljs file - smooth like butter

Since 2 of the files @thheller mentioned earlier in the thread are also .cljc I'm thinking that might be something worth looking into.

The file I'm experiencing this on is part of an open source project I'll be releasing in a few days, so you'll be able to look into it yourself then.

@cursive-ide I can't re-open the issue since you closed it - would you?

**Comment by cursive-ide** [comment] 2017-04-18 08:14
@gnl Ok, thanks - if you could let me know when you release it I'll take a look. I'll also go back tomorrow and try to reproduce using @thheller's files again.

**Comment by cursive-ide** [comment] 2017-04-18 08:26
@gnl Actually, if you have time, could you record another similar snapshot? Then I can see if anything has changed. It'll be helpful in case I can't reproduce, too - I tried previously using @thheller's files but couldn't.

**Comment by gnl** [comment] 2017-04-18 08:45
@cursive-ide There you go:

[IU-171.4073.35_gnl_18.04.2017_11.33.53.zip](https://github.com/cursive-ide/cursive/files/927944/IU-171.4073.35_gnl_18.04.2017_11.33.53.zip)

The snapshot is from eap7, it's me typing gibberish as fast as possible during an inline rename of a binding in a small function. To give you an idea of the input lag during the refactoring, when typing really fast for about 2 seconds, it takes another 2-3 seconds for the text to appear completely on screen (it's displayed in chunks).

Will let you know when I release (could be a week though, polishing things left and right, doing some more dogfooding, you know how it is).

**Comment by thheller** [comment] 2017-04-18 09:55
The things @gnl mentions all sound familiar, I'm using IdeaVIM as well. I couldn't reproduce this yet but one thing that was the show-stopper for me was that I couldn't even scroll/navigate through certain files without extensive lag. Sometimes waiting several seconds to scroll a few lines.

I'll try the new EAP later today. Downgraded to 1.4.3 and didn't have issues since then.

**Comment by cursive-ide** [comment] 2017-04-19 09:17
@gnl I reproduced what you're seeing with the input lag during refactoring, but I also see that with 1.4.3 - it doesn't appear to be new in this EAP series. Can you confirm which version you upgraded from? I was working from the assumption that this was a new issue, but perhaps it's not.

**Comment by gnl** [comment] 2017-04-19 10:04
@cursive-ide - yes, I mentioned that I tested with 1.4.3 as well in a previous comment, maybe I wasn't quite clear - my input lag issue doesn't appear to be new, in fact it seemed even worse in eap1 and older (incl. 1.4.3).

The fact that I first encountered it after an upgrade was likely a coincidence (I think it was about that time that I migrated my macros to a .cljc file). It's also quite possible that the issues encountered here aren't the same, as @thheller mentioned he was doing fine after the downgrade to 1.4.3.

**Comment by gnl** [comment] 2017-04-19 10:05
And to confirm - I've been on the EAP channel for as long as I can remember, only downgraded to 1.4.3 now in order to test and now I'm back on eap7.

**Comment by cursive-ide** [comment] 2017-04-19 10:23
You're absolutely right, my apologies - I re-read your original but not your recent one after re-testing. Ok, I'll see if I can fix your issue and reproduce something like what @thheller is seeing. @thheller, if you could confirm when you've tried eap7 to see if the fix helps the problem you're seeing?

**Comment by thheller** [comment] 2017-04-27 07:42
Just saw the bad input lag while editing a plain ~100 LOC `.clj` file on eap8. Just adding/removing a new line caused significant (>2sec) input lag before the next thing happened.

The issue is gone after restarting IDEA, can't really say how it got bad.

**Comment by thheller** [comment] 2017-04-28 15:02
This might not be related to Cursive after all. I just saw the same input lag while editing a `.java` file. This was on the usual Clojure project with many open .clj files though so I can't really tell.

**Comment by cursive-ide** [comment] 2017-05-02 01:59
I'm going to push this out. It seems unclear whether @thheller's problem is Cursive related, I've investigated a snapshot and I can't see anything suggesting Cursive is holding up the EDT there. I reproduced @gnl's problem, but that's been present for some time so I'm not going to hold up this release for it. I'm moving it into the next release and I'll look at it again there.

**Comment by thheller** [comment] 2017-05-02 09:01
Yeah my issue is funky, don't hold back because of that. I misread the snapshot and the lazy seq is not on the UI thread.

I can't quite narrow down the issue, sometimes everything just works and then it doesn't. Maybe the issue gets more apparent when more people start using the latest code. Or it really is just me and my weird setup.

**Comment by pmoriarty** [comment] 2017-07-04 08:03
I have a serious High CPU/UI lag issue since moving to 1.6.0. It happens frequently and I can't pinpoint a usage pattern that triggers it. Episodes seem to last minutes and CPU usage stays above 100% (of 800%) all that time. It often goes up to 400% for shorter periods.

Attaching CPU profiling dump. UI was very laggy for most of the time.

[IU-171.4694.23_pmoriarty_04.07.2017_08.54.23.zip](https://github.com/cursive-ide/cursive/files/1121324/IU-171.4694.23_pmoriarty_04.07.2017_08.54.23.zip)

**Comment by cursive-ide** [comment] 2017-07-06 03:57
@pmoriarty So honestly, I'm not sure what's going on there. Your dumps show some CPU spikes:

![screen shot 2017-07-06 at 15 13 19](https://user-images.githubusercontent.com/5589171/27894510-a7daed3e-6260-11e7-9f28-394cffb88c73.png)

![screen shot 2017-07-06 at 15 13 56](https://user-images.githubusercontent.com/5589171/27894516-ae66f31e-6260-11e7-80d6-1b5f18955f51.png)

![screen shot 2017-07-06 at 15 14 20](https://user-images.githubusercontent.com/5589171/27894524-b8786da6-6260-11e7-8f60-bb97f3a44979.png)

But they don't look anywhere as extreme as what you're describing. And between those two or three spikes, there's basically tumbleweeds:

![screen shot 2017-07-06 at 15 14 43](https://user-images.githubusercontent.com/5589171/27894531-c6c53eb6-6260-11e7-95af-42327271e6f4.png)

There is one thing that seems to be going on during some of those spikes, which is an interaction between the Groovy plugin and Cursive. I'm going to talk to JetBrains about that, since it looks like I'm doing some work which may be unnecessary there.

**Comment by cursive-ide** [comment] 2017-09-04 04:22
I'm going to close this issue now. I've filed #1841 to track @gnl's issue which has been around for a while. I believe both @thheller's and @pmoriarty's are now fixed.

This issue ended up with several unrelated problems in it. If one of them reoccurs, please file a new issue and link this one rather than re-opening this one.

**Closed by cursive-ide** 2017-09-04 04:22 UTC
