### ISSUE TITLE
IndexNotReadyException on IDEA 2018.2

### ISSUE THREAD

**Issue by p-himik** [cursive-ide/cursive#2016] opened 2018-07-27 07:44 UTC
Upgraded IDEA to 2018.2, upgraded all plugins, started seeing this error:
```
Error while indexing /home/p-himik/.m2/repository/binaryage/oops/0.6.2/oops-0.6.2.jar!/oops/defaults.clj
To reindex this file IDEA has to be restarted

com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
t com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:77)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:774)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:723)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:894)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValueIterator(FileBasedIndexImpl.java:970)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:941)
	at com.intellij.util.indexing.FileBasedIndexImpl.getValues(FileBasedIndexImpl.java:802)
	at cursive.index$values_by_ns.invoke(index.clj:327)
[...]
```

Tried switching Boot JDK to the bundled one and reindexing - issue persists.

I reported the error from within IDEA.

**Comment by cursive-ide** [comment] 2018-07-27 08:13
I think this is a dupe of #1985 and #1996 which are both fixed in the next EAP. It should be out on Monday.

**Closed by cursive-ide** 2018-07-27 08:13 UTC
