### ISSUE TITLE
deps.edn alias overrides from `~/.clojure/deps.edn` fail if they contain '/'

### ISSUE THREAD

**Issue by raymcdermott** [cursive-ide/cursive#2161] opened 2019-04-22 17:13 UTC
This seems to be a regression as my old local override aliases worked fine.

Changing `my/alias` to `my-alias` works as a fix.

Cursive v1.8.1-2019.1
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

**Comment by cursive-ide** [comment] 2019-05-05 04:49
When you say they fail, what do you mean?

**Comment by cursive-ide** [comment] 2019-05-05 05:01
I've fixed one bug where there was a warning in the run config panel that the alias name isn't valid (but that would still let you do what you need to do), but I can't find anything else. Let me know if there are further problems here that need attention.

**Comment by raymcdermott** [comment] 2019-05-05 08:21
I mean it’s ignored

**Comment by cursive-ide** [comment] 2019-05-05 22:25
I can't reproduce that. I've managed to:

1. Select the alias in the Clojure Deps toolwindow, and had the values take effect in the project sync.
2. Add the alias to a run configuration, get it passed to deps and have it take effect.

Can you specify exactly what is failing for you?

**Comment by raymcdermott** [comment] 2019-05-06 08:21
I’ll check my setup again with your latest build and report back

**Closed** 2019-05-18 05:08 UTC
Labels: deps.edn

**Comment by raymcdermott** [comment] 2019-12-17 18:30
I'm experiencing this again 
![image](https://user-images.githubusercontent.com/120437/71023778-bd229480-2103-11ea-99e4-b3a5525dc40e.png)

**Comment by raymcdermott** [comment] 2019-12-17 18:32
![image](https://user-images.githubusercontent.com/120437/71023863-ec390600-2103-11ea-8812-7998c423a13f.png)

**Comment by raymcdermott** [comment] 2019-12-17 18:36
➜ java -version 
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b05)
OpenJDK 64-Bit Server VM (build 25.222-b05, mixed mode)
➜ clojure              
Clojure 1.10.1
user=> 
![image](https://user-images.githubusercontent.com/120437/71024096-77b29700-2104-11ea-830c-7f98c3244da3.png)

**Comment by raymcdermott** [comment] 2019-12-17 18:37
![image](https://user-images.githubusercontent.com/120437/71024159-97e25600-2104-11ea-8547-6fbc66bd718b.png)

**Comment by raymcdermott** [comment] 2019-12-17 19:34
the current project is Clojure
- the project called `sdk-data` is CLJC 
- I'm using SSH for the git deps when they're not served through `:local/root`
