### ISSUE TITLE
Unable to generate stubs with datomic 0.9.5561.50

### ISSUE THREAD

**Issue by neuromantik33** [cursive-ide/cursive#1810] opened 2017-07-19 12:23 UTC
Hello,

I recently migrated to the latest version of datomic and when prompted to generate stubs I get the following error

```
Error generating stubs for module schlumpf-master-1: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at ...
```

My project has a dependency with clojure 1.8.0 and I verified in the pom.xml of the datomic jar (which seems to be the culprit) and it has a dependency on 1.8.0 as well. Is there any way to log the missing class  so that I can investigate further?

Thanks in advance, Nick

**Comment by cursive-ide** [comment] 2017-07-19 22:36
No, there isn't - unfortunately EIIEs are hard to debug. I'll upgrade datomic in my test repo and see if I can reproduce.

**Comment by neuromantik33** [comment] 2017-07-20 04:37
No worries, I found the problem.. I obviously had a problem with transitive dependencies (duh) and it was much more apparant when reading the ClassNotFoundException below (which seems to be truncated by stub generation but not by leiningen. Anyhow thanks anyways and if you ever support your own gradle plugin instead of lein do let me know ;)

**Comment by cursive-ide** [comment] 2017-07-24 00:11
Actually: [gradle-clojure](https://github.com/cursive-ide/gradle-clojure) :-)

BTW there was no ClassNotFoundException in your last comment, I'd be interested to see that so I can try to figure out how to improve the logging there.

That said, it looks like the original issue isn't actually a bug, so I'll close this issue.

**Closed by cursive-ide** 2017-07-24 00:11 UTC
