### ISSUE TITLE
Unable to find or copy inside repl result text box.

### ISSUE THREAD

**Issue by fredlellis** [cursive-ide/cursive#1381] opened 2016-04-28 18:53 UTC
Hi guys,  recently i updated my cursive and now i cant use find text and copy from local repl result text area.I have to allow  these features somewhere? 

Thankyou for your time and congratulation for the work!

**Comment by plcstevens** [comment] 2016-04-29 09:57
I am also having this problem with latest update. Unable to find/copy text from within the REPL.

**Comment by cursive-ide** [comment] 2016-04-29 10:32
A few people have reported this - I'm not sure what's going on there, I'll investigate.

**Comment by cursive-ide** [comment] 2016-04-29 10:34
In fact, this is a dupe of #1380, I'll close this one.

**Closed by cursive-ide** 2016-04-29 10:34 UTC
