### ISSUE TITLE
Add namespace into :require in alphabetical order

### ISSUE THREAD

**Issue by madvas** [cursive-ide/cursive#1592] opened 2016-11-24 08:35 UTC
While cursive's feature to automatically require namespace is super useful, thanks for that!, it would be even better if instead of adding it as last item, it adds it in alphabetical order. It is considered good practice in clojure community to keep requires in alphabetical order. 

https://stuartsierra.com/2016/clojure-how-to-ns.html#sorting

So let's say I already have:
```clojure
(ns my.namespace
  (:require
    [aaa.core :as aaa]
    [ccc.core :as ccc]))
```
And cursive would auto add `bbb.core` like this:
```clojure
(ns my.namespace
  (:require
    [aaa.core :as aaa]
    [bbb.core :as bbb]
    [ccc.core :as ccc]))
```

**Comment by cursive-ide** [comment] 2016-11-24 09:12
This issue is a dupe of #77  and #1197.

**Closed by cursive-ide** 2016-11-24 09:12 UTC

**Comment by ertugrulcetin** [comment] 2020-11-09 17:40
@madvas I wrote a lein plugin for ns sorting, might help: https://github.com/ertugrulcetin/lein-nsort
