### ISSUE TITLE
Weird cljc ns indentation

### ISSUE THREAD

**Issue by thheller** [cursive-ide/cursive#1474] opened 2016-07-26 17:12 UTC
I have an `ns` form in a `.cljc` which cursive (1.3.0) indents very weirdly.

```clojure
(ns my-ns
  #?@(:clj
      [
       (:require [a :as b])]
      :cljs
      [(:require-macros [a :as c])
       (:require [c :as b])]))
```

Note the extra newline after the `[`?

```clojure
(ns my-ns
  #?@(:clj
      [(:require [a :as b])]
      :cljs
      [(:require-macros [a :as c])
       (:require [c :as b])]))
```
 I expect this but every time I press `reformat code` things go back to the above.

**Comment by mtruyens** [comment] 2016-07-27 06:13
Seems like a duplicate of https://github.com/cursive-ide/cursive/issues/1014

**Comment by danielcompton** [comment] 2016-09-01 02:42
Yep, dupe.

**Closed by danielcompton** 2016-09-01 02:42 UTC
Labels: CLJC
