### ISSUE TITLE
Double source paths

### ISSUE THREAD

**Issue by mtruyens** [cursive-ide/cursive#1223] opened 2016-01-18 20:39 UTC
In a cross-CLJ/CLJS project, I include a package with .cljc files in both the CLJ-part of the project.clj file, and in the CLJS-part of the project.clj file. 

As a result, when I search for a symbol that is located within that package, I get two identical results.

**Comment by danielcompton** [comment] 2016-05-18 21:55
Dupe of #1132.

**Closed by danielcompton** 2016-05-18 21:55 UTC
