### ISSUE TITLE
Stub generation fails Cursive 1.9.0-eap2-2019.3 (also 2019.2)

### ISSUE THREAD

**Issue by juskrey** [cursive-ide/cursive#2242] opened 2019-10-02 14:59 UTC
Cursive 1.9.0-eap2-2019.3

`java.lang.ClassCastException: class com.intellij.idea.IdeaLogger cannot be cast to class org.apache.log4j.Category (com.intellij.idea.IdeaLogger and org.apache.log4j.Category are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @6767c1fc)
	at cursive.stubs$stubs_required$fn__265.invoke(stubs.clj:374)
	at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8159.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8136.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8136.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$reduce.invoke(core.clj:6810)
	at cursive.stubs$stubs_required.invokeStatic(stubs.clj:373)
	at cursive.stubs$stubs_required.invoke(stubs.clj:365)
	at clojure.lang.Var.invoke(Var.java:388)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:36)
	at cursive.stubs.ReplStubsNotifications$checkStubs$1.run(Stubs.kt:202)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by cursive-ide** [comment] 2019-10-03 06:14
Yes, quite a few people have reported this, but I can't reproduce it. I'll try again tomorrow.

**Comment by cursive-ide** [comment] 2019-10-04 03:27
This is fixed in the next build.

**Closed by cursive-ide** 2019-10-04 03:27 UTC
