### ISSUE TITLE
UI freeze when i press enter to complete (and auto-require) a suggestion

### ISSUE THREAD

**Issue by moizsj** [cursive-ide/cursive#1457] opened 2016-07-11 06:21 UTC
I type an ns alias and symbol (that hasnt yet been required), get a suggestion matching my inputs (like "abcd/some-fn"), hit enter after picking the one I want from the list. And then the UI freezes.
Attached thread dump.
[threadDumps-20160711-114532-IC-143.1184.zip](https://github.com/cursive-ide/cursive/files/356531/threadDumps-20160711-114532-IC-143.1184.zip)

**Comment by cursive-ide** [comment] 2016-07-18 02:48
This actually appears to be a problem in the Kotlin plugin - there's nothing in that thread dump mentioning Cursive at all. Note that a bug can appear in one plugin through an action invoked in another - for example, it's possible that the action you performed looks for available classes, which will query all installed plugins.

I'm going to close this since I believe the problem to be elsewhere. If you see a reason to think otherwise, feel free to reopen this.

**Comment by moizsj** [comment] 2016-07-18 07:57
Re-opening. Was able to reproduce even after disabling the Kotlin plugin. Attaching fresh thread dumps. Can see calls into Cursive for code completion.

[20160718-132033.zip](https://github.com/cursive-ide/cursive/files/368534/20160718-132033.zip)

**Comment by cursive-ide** [comment] 2016-07-19 23:09
Actually, I'm going to close this, since it appears to be a duplicate of #1246.

**Closed by cursive-ide** 2016-07-19 23:09 UTC
