### ISSUE TITLE
REPL caches previous results when testing.REPL does not produce correct Results!

### ISSUE THREAD

**Issue by ertugrulcetin** [cursive-ide/cursive#1537] opened 2016-09-24 12:49 UTC
I can not test my functions in REPL.

Tests are passing when I manually execute **(clojure.test/run-tests *my-test-namespace*)**.

If I try to use **REPL for Testing** Results become **wrong** and some Tests Fail(**_Occasionally_**)!

I think there is some cache mechanism

**Comment by cursive-ide** [comment] 2016-09-24 20:05
Cursive doesn't have any caching mechanism, in fact it just delegates to clojure.test. However it does monkey patch clojure.test a fair amount, so there may be something about your tests that provokes a bug. Is it always the same tests which fail? Is there anything odd or complicated about how those tests work? Any concurrency involved, or anything like that?

**Comment by ertugrulcetin** [comment] 2016-09-24 20:36
No tests don't have any concurrent code and nothing is odd.There are other
tests too I can assure you that tests have nothing do with this problem.

If I run (clojure.test/run-tests my-namespace) it shows me the current new
results(no problem).

On the other hand, sometimes REPL shows the previous results after I change
the code like changing true to false.

I have to re-run REPL for the current and correct results.

Please check this issue, it is very important.If you can't still understand
the problem I can record a video for this.

**Comment by cursive-ide** [comment] 2016-09-24 23:32
A video would be useful, thanks.

**Comment by ertugrulcetin** [comment] 2016-09-25 07:43
I've recorded a video. Could you send me a email address so I can post it.

**Comment by cursive-ide** [comment] 2016-09-25 19:23
You can send it to cursive@cursive-ide.com - thanks.

**Comment by cursive-ide** [comment] 2016-09-25 22:05
Ok, I don't think there's a bug here, it's just not clear when code is being loaded into the REPL. The key thing is that when code is modified in the editor, it will not be loaded automatically into the REPL but Cursive will load it when certain commands are run, in particular the test commands.

Here's what happens:

1. At the beginning, I guess the code loaded into the REPL corresponds to the editor, you run the tests using `(run-tests)` at 0.08 and it works correctly.
2. You then modify the code in the editor and break the test, but you don't reload the changed code into the REPL, so the REPL is still running the previous code. `(run-tests)` at 0:22 continues to work, because the old code is still running, and the test is still valid.
3. At 0:31 you then run the tests using Cursive's test functionality. Cursive loads any code which is out of date with what's running in the REPL, and correctly reports that the test is broken.
4. You then use `(run-tests)` at 0:37, which correctly reports that the test is broken - this is because Cursive has just loaded the code from the editor at step 3, and the code in the REPL corresponds to the editor.
5. You then fix the tests and use `(run-tests)` again at 0:44, but again without loading the code so the broken test is what is still loaded into the REPL. `run-tests` thus still reports that the code is broken.

The reason that `(run-tests)` always works when you execute the file is that that starts a new process and loads the test namespace, so the loaded code is always what is in the editor.

The basic issue is that `(run-tests)` will not automatically load the code. Cursive's test functionality will, and is generally recommended. Do you have a reason for not wanting to use that?

Stuart Sierra gave [a talk](https://www.youtube.com/watch?v=-RaFcpNiYCo) at Clojure/West this year about this sort of problem.

I'm going to close this because it's not a bug.

**Closed by cursive-ide** 2016-09-25 22:05 UTC
