### ISSUE TITLE
Rename of destructured map args using :keys attempts to refactor too much

### ISSUE THREAD

**Issue by akombo** [cursive-ide/cursive#1208] opened 2016-01-07 19:42 UTC
When attempting to use the "rename" refactoring to rename id in the following screen capture the IDE first warned me "'id' destructures keyword ':id'. Do you want to rename the keyword?" and when I clicked "Yes" it brought up a window for a project-wide refactoring, as if I had done a mass search and replace.

Here is the function to be refactored:
![screenshot from 2016-01-07 11 12 07](https://cloud.githubusercontent.com/assets/901468/12180708/db35b964-b543-11e5-8295-72751e3dec89.png)

Here is the dialog that greeted me next:
![screenshot from 2016-01-07 13 34 38](https://cloud.githubusercontent.com/assets/901468/12180728/ea302738-b543-11e5-8b68-3395f37a1fe0.png)

Here are a couple shots of the list of possible refactorings it had found:

![screenshot from 2016-01-07 11 12 56](https://cloud.githubusercontent.com/assets/901468/12180749/019cf9dc-b544-11e5-8d55-dd890e7e5a9c.png)

![screenshot from 2016-01-07 11 21 49](https://cloud.githubusercontent.com/assets/901468/12180754/082b6dba-b544-11e5-91e7-882c3f251e1b.png)

**Comment by cursive-ide** [comment] 2016-01-07 21:55
So this is a combination of expected behaviour and a bug. It's expected that when you say you want to rename the keyword it should be a global operation - keywords are global, after all. But it's confusing how it's worded - it should really be "Do you want to rename the keyword or just the local variable?" with "Rename ':id' keyword" and "Rename 'id' local" buttons. This would make it clearer what it's actually asking.

The bug is that if you choose to rename the keyword, the rename is finding all symbols *containing* the name of the keyword, which is clearly wrong. It should not pick up `rds-id` or `loop-id` in your example, obviously. I'll fix that ASAP, that's obviously pretty bad. I suspect it's not generally a problem because most keywords have longer names than `id`, so this case shows the bug off more than others would tend to.

**Comment by akombo** [comment] 2016-01-08 20:18
Thanks for looking at this as quickly as you have. I agree that changing the language of the dialog will make the behavior more clear.

**Comment by cursive-ide** [comment] 2016-01-09 00:35
Fixing the bug will no doubt help as well :-)

**Comment by cursive-ide** [comment] 2016-06-13 04:40
This is a duplicate of #800.

**Closed by cursive-ide** 2016-06-13 04:40 UTC
