### ISSUE TITLE
Intellij got completely frozen - AWT thread stuck in cursive.formatting.ElementBlock.getSubBlocks

### ISSUE THREAD

**Issue by sdomin** [cursive-ide/cursive#1237] opened 2016-01-31 21:38 UTC
After my PC woke from sleep, intellij was frozen and using 1 core at 100%
Restart didn't help - as soon as it tried to reopen the last project, it got stuck again.
I managed to get around the issue by opening Intellij, cancelling project loading and then running "Invalidate caches/Restart" action, which did help.

Here are couple stack traces from when it was stuck:
```
"AWT-EventQueue-0 IDEA 15.0.3#IU-143.1821.5 IDEA, eap:false, os:Windows 8 6.2, java-version:Oracle Corporation 1.8.0_20-b26" #24 prio=6 os_prio=0 tid=0x00000000188b2000 nid=0x3460 runnable [0x000000001bcd9000]
   java.lang.Thread.State: RUNNABLE
        at cursive.resolve$light_keys.invoke(resolve.clj:168)
        at cursive.resolve$resolve_keys.invoke(resolve.clj:179)
        at cursive.formatting$list_block_params.invoke(formatting.clj:223)
        at cursive.formatting$basic_block_params.invoke(formatting.clj:304)
        at cursive.formatting$sub_blocks.invoke(formatting.clj:314)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$memoize$fn__5479.doInvoke(core.clj:6082)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at cursive.formatting.ElementBlock.getSubBlocks(formatting.clj:34)
        at com.intellij.psi.formatter.common.NewLineBlocksIterator.b(NewLineBlocksIterator.java:115)
        at com.intellij.psi.formatter.common.NewLineBlocksIterator.next(NewLineBlocksIterator.java:86)
        at com.intellij.psi.codeStyle.autodetect.FormatterBasedLineIndentInfoBuilder.a(FormatterBasedLineIndentInfoBuilder.java:133)
        at com.intellij.psi.codeStyle.autodetect.FormatterBasedLineIndentInfoBuilder.build(FormatterBasedLineIndentInfoBuilder.java:49)
        at com.intellij.psi.codeStyle.autodetect.IndentOptionsDetectorImpl.a(IndentOptionsDetectorImpl.java:73)
        at com.intellij.psi.codeStyle.autodetect.IndentOptionsDetectorImpl.getIndentOptions(IndentOptionsDetectorImpl.java:56)
        at com.intellij.psi.codeStyle.autodetect.DetectableIndentOptionsProvider.getIndentOptions(DetectableIndentOptionsProvider.java:56)
        at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptionsByFile(CodeStyleSettings.java:672)
        at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptionsByFile(CodeStyleSettings.java:636)
        at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptionsByFile(CodeStyleSettings.java:631)
        at com.intellij.openapi.editor.impl.SettingsImpl.b(SettingsImpl.java:334)
        at com.intellij.openapi.editor.impl.SettingsImpl.reinitSettings(SettingsImpl.java:319)
        at com.intellij.openapi.editor.impl.EditorImpl.reinitSettings(EditorImpl.java:795)
        at com.intellij.openapi.editor.impl.EditorImpl.setHighlighter(EditorImpl.java:1186)
        at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.d(TextEditorComponent.java:168)
        at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.<init>(TextEditorComponent.java:100)
        at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:62)
        at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:55)
        at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.createEditorComponent(PsiAwareTextEditorImpl.java:44)
        at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.<init>(TextEditorImpl.java:46)
        at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.java:38)
        at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$1.build(PsiAwareTextEditorProvider.java:77)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13.run(FileEditorManagerImpl.java:873)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
        at java.awt.EventQueue.access$400(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.awt.EventQueue$3.run(EventQueue.java:691)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
        at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:866)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
        at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:953)
        at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:210)
        at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:197)
        at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:650)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:354)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:230)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:183)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:371)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:467)
        at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:182)
        at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:46)
        at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:554)
        at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:588)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
        at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:368)
        at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:355)
        at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:334)
        at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
        at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:223)
        at com.sun.proxy.$Proxy45.appStarting(Unknown Source)
        at com.intellij.idea.IdeaApplication$IdeStarter$2.run(IdeaApplication.java:354)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
        - locked <0x00000000e567f728> (a java.lang.Object)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
        at java.awt.EventQueue.access$400(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.awt.EventQueue$3.run(EventQueue.java:691)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
        at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:866)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
and
```
"AWT-EventQueue-0 IDEA 15.0.3#IU-143.1821.5 IDEA, eap:false, os:Windows 8 6.2, java-version:Oracle Corporation 1.8.0_20-b26" #24 prio=6 os_prio=0 tid=0x0000000016573000 nid=0x2418 runnable [0x000000001bc8a000]
   java.lang.Thread.State: RUNNABLE
        at clojure.lang.RT.get(RT.java:721)
        at cursive.resolve$light_keys.invoke(resolve.clj:164)
        at cursive.resolve$resolve_keys.invoke(resolve.clj:179)
        at cursive.formatting$list_block_params.invoke(formatting.clj:223)
        at cursive.formatting$basic_block_params.invoke(formatting.clj:304)
        at cursive.formatting$sub_blocks.invoke(formatting.clj:314)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$memoize$fn__5479.doInvoke(core.clj:6082)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at cursive.formatting.ElementBlock.getSubBlocks(formatting.clj:34)
.....
```

**Comment by cursive-ide** [comment] 2016-01-31 23:10
This is a duplicate of #1210 - see over there for a workaround.

**Closed by cursive-ide** 2016-01-31 23:10 UTC

**Comment by sdomin** [comment] 2016-01-31 23:17
Thanks. Sorry, missed the original one when creating mine.
