### ISSUE TITLE
Java interop: Element type inferred as abstract class implemented by correct type

### ISSUE THREAD

**Issue by goodgerster** [cursive-ide/cursive#2375] opened 2020-05-20 23:58 UTC
## Symptom

Cursive gives a ‘cannot be resolved’ warning on a valid Java method call in my Clojure code.

### Environment

I am using Clojure 1.10.1, IntelliJ IDEA 2020.1.1 (build 201.7223.91), ICU4J 67.1, and Cursive 1.9.2-eap4-2020.1 on Arch Linux. IDEA is running on Jetbrains JRE 11.0.6+8-b765.40.amd64; the project JDK is OpenJDK 11.0.6; and the project language level is 11.

### Reproduction

This code works correctly when executed:
```clojure
(defn euro-format [amount]
  (-> (NumberFormatter/withLocale          ;; com.ibm.icu.number.NumberFormatter
        (ULocale. "nl"))                   ;; com.ibm.icu.util.ULocale
      (.unit (Currency/getInstance "EUR")) ;; com.ibm.icu.util.Currency
      (.format amount)
      str))
;; => #'user/euro-format

(euro-format 123456.789)
;; => "€ 123.456,79"
```

Cursive highlights `.format` and gives the warning:
> format cannot be resolved

### Apparent cause

The `format` method called belongs to `com.ibm.icu.number.LocalizedNumberFormatter`, an instance of which is returned by `NumberFormatter.unit` ([as documented](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/number/NumberFormatter.html#withLocale-com.ibm.icu.util.ULocale-)).

### Failed workaround

`LocalizedNumberFormatter` is not mentioned in my code, and importing it explicitly does not help.

## Expected behaviour

* The `format` call can be inferred to apply to the return value of the `unit` call (it is inside a standard threading macro).
* The `unit` call can itself be inferred to return an instance of `LocalizedNumberFormatter` (all methods named `unit` are statically typed as `LocalizedNumberFormatter`).
* Through these inferences, Cursive should be able to resolve the method correctly.

**Comment by cursive-ide** [comment] 2020-05-21 05:31
Cursive actually does perform the type inference you suggest, so there's something else going on. You can debug where the problem is happening using the "Show Element Type" action which will show the type of the form at the caret. To check the return type of a function invocation, put the caret before the opening paren.

**Comment by goodgerster** [comment] 2020-05-21 08:03
Thanks for the reply. The output from ‘Show Element Type’ on the `(.unit …)` form is `com.ibm.icu.number.NumberFormatterSettings`, the abstract class implemented by `LocalizedNumberFormatter`.

**Comment by cursive-ide** [comment] 2020-05-21 11:24
What are the deps you're using for this project related to this? I tried to reproduce using `{com.ibm.icu/icu4j {:mvn/version "2.6.1"}}` but classes like `NumberFormatter` are not present, and Maven Central search doesn't come up with anything for them.

**Comment by cursive-ide** [comment] 2020-05-21 11:37
BTW the Javadoc you linked doesn't actually show a `unit()` method on `NumberFormatter`, you have to call `NumberFormatter.with()` to get an `UnlocalizedNumberFormatter` which does have that method. I'm not sure if that API corresponds to the version you're using though.

**Comment by goodgerster** [comment] 2020-05-21 15:58
I’m on `{com.ibm.icu/icu4j {:mvn/version "67.1"}}` so I imagine 2.6.1 probably differs considerably.…

And sorry, that seems to have been the wrong link. That’ll teach me not to write bug reports in the small hours.

To clarify, unless I have things badly misinterpreted, the expected usage is:
* [`NumberFormatter.withLocale`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/number/NumberFormatter.html#withLocale-com.ibm.icu.util.ULocale-) returns a [`LocalizedNumberFormatter`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/number/LocalizedNumberFormatter.html)
* on that I call [`unit`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/number/NumberFormatterSettings.html#unit-com.ibm.icu.util.MeasureUnit-) (inherited from [`NumberFormatterSettings`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/number/NumberFormatterSettings.html))
* this returns another `LocalizedNumberFormatter`
* on that I call [`format`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/number/LocalizedNumberFormatter.html#format-double-)
* this finally returns a [`FormattedNumber`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/number/FormattedNumber.html).

Thanks for your time.

**Comment by cursive-ide** [comment] 2020-05-21 22:29
Ah, I see the problem. The problem is that `unit` has a generic return type of `T`, but Clojure doesn't understand generics. So the actual return type in the bytecode is the lower bound of the generic, which is NumberFormatterSettings. So while your code works, it requires reflection on every invocation to work:
```
Clojure 1.10.1
(set! *warn-on-reflection* true)
=> true
Loading src/cursive_2375/core.clj... 
Reflection warning, /Users/colin/dev/cursive-bugs/cursive-2375/src/cursive_2375/core.clj:9:7 - call to method format on com.ibm.icu.number.NumberFormatterSettings can't be resolved (no such method).
Loaded
```

The solution is to use type hinting to inform Clojure (and Cursive) what the real type is:
```
(defn euro-format [amount]
  (let [^LocalizedNumberFormatter formatter
        (-> (NumberFormatter/withLocale
              (ULocale. "nl"))
            (.unit (Currency/getInstance "EUR")))]
    (-> formatter
        (.format amount)
        str)))
```
That still has a problem because `amount` is not type hinted, and `format` is overloaded:

<img width="405" alt="Screen Shot 2020-05-22 at 10 27 39" src="https://user-images.githubusercontent.com/5589171/82612411-53c31800-9bb2-11ea-9f92-229e46952eca.png">

You can see the available overloads using parameter info:

<img width="411" alt="Screen Shot 2020-05-22 at 10 28 12" src="https://user-images.githubusercontent.com/5589171/82612444-689fab80-9bb2-11ea-9521-c74df2a375fe.png">

I'm going to close this since it's not actually a Cursive problem.

**Closed by cursive-ide** 2020-05-21 22:29 UTC
