### ISSUE TITLE
if-let doesn't bind in the else expression

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1654] opened 2017-02-01 08:44 UTC
```clj
(if-let [data nil]
  data
  data)
```

The `data` in the else expression is seen by Cursive as being bound by the `if-let`, and as a valid symbol, but it won't compile. 

I discovered this when doing a refactoring on a function parameter `data`, as it didn't correctly rename `data` on the fifth line.

```clj
(defn cljs-builds [data]
  (map-to-vec-builds
   (let [res (if-let [data (figwheel-edn)]
               (:builds data)
               (let [cnf (fuz/fuzzy-select-keys-and-fix data [:cljsbuild :figwheel])]
                 (or (get-in cnf [:figwheel :builds]) (get-in cnf [:cljsbuild :builds]))))]
     (if (coll? res) res []))))
```

**Comment by cursive-ide** [comment] 2017-02-01 10:07
This is a dupe of #500.

**Closed by cursive-ide** 2017-02-01 10:07 UTC

**Comment by danielcompton** [comment] 2017-02-01 19:14
Oops, sorry.
