### ISSUE TITLE
Cursive deadlock on IDEA startup when upgrading to the latest version

### ISSUE THREAD

**Issue by chajath** [cursive-ide/cursive#1508] opened 2016-08-26 19:18 UTC
Here is the deadlock from thread dump. I had to redact a few lines there, in order to not expose stack trace from a plugin in use internally. Basically the plugin manages and installs company-wide coding style.

If you need more information wrt the specifics of the plugin, I will see if I can clear it with the company to provide you more information.

```
Found one Java-level deadlock:
=============================
"ApplicationImpl pooled thread 2":
  waiting to lock monitor 0x00007fb25eaa5788 (object 0x00000006ec97b2f8, a java.lang.Object),
  which is held by "AWT-EventQueue-0 2016.2.1#IU-162.1447.26 IDEA, eap:false, os:Linux 3.13.0-92-generic, java-version:JetBrains s.r.o 1.8.0_76-release-b216"
"AWT-EventQueue-0 2016.2.1#IU-162.1447.26 IDEA, eap:false, os:Linux 3.13.0-92-generic, java-version:JetBrains s.r.o 1.8.0_76-release-b216":
  waiting to lock monitor 0x00007fb25eaa5418 (object 0x00000006ed3ba1e0, a java.lang.Object),
  which is held by "ApplicationImpl pooled thread 2"

Java stack information for the threads listed above:
===================================================
"ApplicationImpl pooled thread 2":
	at cursive.config.InitComponent.initClojure(InitComponent.java:89)
	- waiting to lock <0x00000006ec97b2f8> (a java.lang.Object)
	at cursive.formatter.codeStyle.ClojureCodeStyleSettings.<init>(ClojureCodeStyleSettings.java:38)
	at cursive.formatter.codeStyle.ClojureCodeStyleSettingsProvider.createCustomSettings(ClojureCodeStyleSettingsProvider.java:40)
	at com.intellij.psi.codeStyle.CodeStyleSettings.<init>(CodeStyleSettings.java:76)
	at com.intellij.psi.codeStyle.CodeStyleSettings.<init>(CodeStyleSettings.java:65)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.intellij.openapi.util.DefaultJDOMExternalizer.readExternal(DefaultJDOMExternalizer.java:283)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.loadState(CodeStyleSettingsManager.java:97)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.loadState(CodeStyleSettingsManager.java:33)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:302)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:91)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:237)
	- locked <0x00000006ed395b48> (a com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getInstance(CodeStyleSettingsManager.java:60)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getInstance(CodeStyleSettingsManager.java:43)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getSettings(CodeStyleSettingsManager.java:70)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.a(CodeStyleManagerImpl.java:619)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.<init>(CodeStyleManagerImpl.java:78)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:58)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:232)
	- locked <0x00000006912a2d28> (a com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:41)
	at com.intellij.psi.codeStyle.CodeStyleManager.getInstance(CodeStyleManager.java:47)

(redacted - internal plugin that manages and installs company-wide code style)

	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:302)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:91)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:516)
	- locked <0x00000006912a2f60> (a com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:283)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:222)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.b(ProjectManagerImpl.java:280)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$$Lambda$145/397343506.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:198)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:277)
	- locked <0x00000006eb29aa20> (a com.intellij.configurationStore.StoreAwareProjectManager)
	at com.intellij.ide.fileTemplates.FileTemplateManager.getDefaultInstance(FileTemplateManager.java:67)
	at com.jetbrains.python.packaging.setupPy.CreateSetupPyAction.<init>(CreateSetupPyAction.java:55)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:483)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:151)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:508)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:488)
	- locked <0x00000006ed3ba1e0> (a java.lang.Object)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:481)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1255)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:31)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.application.Preloader$$Lambda$85/1464199974.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.openapi.application.Preloader$$Lambda$84/2014786697.run(Unknown Source)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
"AWT-EventQueue-0 2016.2.1#IU-162.1447.26 IDEA, eap:false, os:Linux 3.13.0-92-generic, java-version:JetBrains s.r.o 1.8.0_76-release-b216":
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:485)
	- waiting to lock <0x00000006ed3ba1e0> (a java.lang.Object)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:481)
	at cursive.actions$unregister_action.doInvoke(actions.clj:31)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at cursive.actions.paredit$initialise.invoke(paredit.clj:836)
	at cursive.initialise$initialise_all.invoke(initialise.clj:41)
	at clojure.lang.Var.invoke(Var.java:375)
	at cursive.config.InitComponent.initClojure(InitComponent.java:122)
	- locked <0x00000006ec97b2f8> (a java.lang.Object)
	at cursive.config.InitComponent.initComponent(InitComponent.java:78)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:518)
	- locked <0x00000006eb86d3f8> (a com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$55/32588350.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:443)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:393)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:385)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:62)
	at com.intellij.idea.MainImpl$1$1$$Lambda$39/262316883.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:358)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Found 1 deadlock.

Heap
 par new generation   total 314560K, used 108184K [0x0000000680000000, 0x0000000695550000, 0x00000006eaaa0000)
  eden space 279616K,  26% used [0x0000000680000000, 0x0000000684786248, 0x0000000691110000)
  from space 34944K, 100% used [0x0000000691110000, 0x0000000693330000, 0x0000000693330000)
  to   space 34944K,   0% used [0x0000000693330000, 0x0000000693330000, 0x0000000695550000)
 concurrent mark-sweep generation total 699072K, used 75790K [0x00000006eaaa0000, 0x0000000715550000, 0x00000007c0000000)
 Metaspace       used 100240K, capacity 106528K, committed 106896K, reserved 1138688K
  class space    used 16313K, capacity 18385K, committed 18484K, reserved 1048576K
```

**Comment by cursive-ide** [comment] 2016-08-27 11:31
Interesting, this is actually an internal deadlock in Cursive. I'll add a fix for this.

**Comment by cursive-ide** [comment] 2016-08-29 01:19
I've added a change that I think should fix this. I can't reproduce it, so please let me know if the problem persists with the next EAP build.

**Closed** 2016-08-29 01:19 UTC
